apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets-k8s
  namespace: todoboard
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []

scopes:
  - backend-service
  - notification-service
  - recurring-task-service
  - audit-service
