{{- if .Values.recurringTaskService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todoboard.fullname" . }}-recurring-task-service
  labels:
    {{- include "todoboard.recurringTaskService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.recurringTaskService.service.type }}
  ports:
    - port: {{ .Values.recurringTaskService.service.port }}
      targetPort: {{ .Values.recurringTaskService.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "todoboard.recurringTaskService.selectorLabels" . | nindent 4 }}
{{- end }}
