apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todoboard.fullname" . }}-dapr-components
  labels:
    {{- include "todoboard.labels" . | nindent 4 }}
data:
  pubsub-kafka.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: pubsub
    spec:
      type: pubsub.kafka
      version: v1
      metadata:
      - name: brokers
        value: "{{ .Values.dapr.components.pubsub.metadata.brokers }}"
      - name: authType
        value: "{{ .Values.dapr.components.pubsub.metadata.authType }}"
      - name: consumerGroup
        value: "todoboard"

  statestore-postgres.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: statestore
    spec:
      type: state.postgresql
      version: v1
      metadata:
      - name: connectionString
        value: "{{ .Values.dapr.components.statestore.metadata.connectionString }}"
