apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todoboard.fullname" . }}-backend-config
  labels:
    {{- include "todoboard.backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.backend }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todoboard.fullname" . }}-frontend-config
  labels:
    {{- include "todoboard.frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.frontend }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
