{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "todoboard.fullname" . }}-db-migration
  labels:
    {{- include "todoboard.labels" . | nindent 4 }}
    component: migration
  annotations:
    {{- range $key, $value := .Values.migration.hookAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "todoboard.selectorLabels" . | nindent 8 }}
        component: migration
    spec:
      restartPolicy: Never
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "todoboard.serviceAccountName" . }}
      containers:
      - name: migration
        image: {{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}
        imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
        command:
          {{- toYaml .Values.migration.command | nindent 10 }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.configMap.backend.DATABASE_URL | quote }}
        envFrom:
        - secretRef:
            name: app-secrets
        resources:
          {{- toYaml .Values.migration.resources | nindent 10 }}
  backoffLimit: 3
{{- end }}
