{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todoboard.fullname" . }}-backend
  labels:
    {{- include "todoboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "todoboard.selectorLabels" . | nindent 4 }}
    app: {{ include "todoboard.fullname" . }}-backend
{{- end }}