{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todoboard.fullname" . }}-frontend
  labels:
    {{- include "todoboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "todoboard.selectorLabels" . | nindent 4 }}
    app: {{ include "todoboard.fullname" . }}-frontend
{{- end }}