"""Add reminder_offset, reminders, and recurring_pattern to tasks table

Revision ID: 2397e6571266
Revises: 010
Create Date: 2026-02-07 19:06:07.752694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2397e6571266'
down_revision = '010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_remind_at'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_sent'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_task_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_recurring_patterns_task_id'), table_name='recurring_patterns')
    op.drop_index(op.f('ix_recurring_patterns_user_id'), table_name='recurring_patterns')
    op.drop_table('recurring_patterns')
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'])
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('USER', 'ASSISTANT', name='messagerole'),
               existing_nullable=False,
               postgresql_using="role::messagerole")
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10000),
               existing_nullable=False)
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('reminder_offset', sa.Integer(), nullable=True))
    op.execute("UPDATE tasks SET reminder_offset = 15 WHERE reminder_offset IS NULL")
    op.alter_column('tasks', 'reminder_offset', existing_type=sa.Integer(), nullable=False)
    # 1. Remove existing server_default for 'status'
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"),
               server_default=None) # Set server_default to None to remove it

    # 2. Alter column type for 'status' with USING clause
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(), # existing_type should reflect what it *was* for this step
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               existing_nullable=False,
               postgresql_using="status::taskstatus")

    # 3. Add new server_default for 'status' with the correct enum cast
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               existing_nullable=False,
               server_default=sa.text("'PENDING'::taskstatus"))
    # 1. Remove existing server_default for 'priority'
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"),
               server_default=None) # Set server_default to None to remove it

    # 2. Alter column type for 'priority' with USING clause
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(), # existing_type should reflect what it *was* for this step
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               existing_nullable=False,
               postgresql_using="priority::taskpriority")

    # 3. Add new server_default for 'priority' with the correct enum cast
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               existing_nullable=False,
               server_default=sa.text("'MEDIUM'::taskpriority"))
    # 1. Remove existing server_default for 'recurring_type'
    op.alter_column('tasks', 'recurring_type',
               existing_type=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"),
               server_default=None) # Set server_default to None to remove it

    # 2. Alter column type for 'recurring_type' with USING clause
    op.alter_column('tasks', 'recurring_type',
               existing_type=sa.VARCHAR(), # existing_type should reflect what it *was* for this step
               type_=sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurringtype'),
               existing_nullable=False,
               postgresql_using="recurring_type::recurringtype")

    # 3. Add new server_default for 'recurring_type' with the correct enum cast
    op.alter_column('tasks', 'recurring_type',
               existing_type=sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurringtype'),
               existing_nullable=False,
               server_default=sa.text("'NONE'::recurringtype"))
    op.drop_index(op.f('ix_tasks_user_id_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_user_id_status'), table_name='tasks')
    op.drop_constraint(op.f('tasks_user_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'scheduled_for_deletion_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'scheduled_for_deletion_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_user_id_fkey'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tasks_user_id_status'), 'tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_user_id_created_at'), 'tasks', ['user_id', 'created_at'], unique=False)
    op.alter_column('tasks', 'recurring_type',
               existing_type=sa.Enum('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurringtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('tasks', 'reminder_offset')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=sa.Enum('USER', 'ASSISTANT', name='messagerole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_table('recurring_patterns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_of_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('recurring_patterns_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('recurring_patterns_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recurring_patterns_pkey'))
    )
    op.create_index(op.f('ix_recurring_patterns_user_id'), 'recurring_patterns', ['user_id'], unique=False)
    op.create_index(op.f('ix_recurring_patterns_task_id'), 'recurring_patterns', ['task_id'], unique=True)
    op.create_table('reminders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('remind_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('sent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('reminders_task_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reminders_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reminders_pkey'))
    )
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_index(op.f('ix_reminders_task_id'), 'reminders', ['task_id'], unique=False)
    op.create_index(op.f('ix_reminders_sent'), 'reminders', ['sent'], unique=False)
    op.create_index(op.f('ix_reminders_remind_at'), 'reminders', ['remind_at'], unique=False)
    # ### end Alembic commands ###